Repository nuxeo/nuxeo-python-client, pull requests merged in 2021-04, with the labels that each got.

#227 NXPY-213: Handle incomplete serialized HTTP error
  CHANGELOG.rst
  nuxeo/client.py
  tests/test_log_response.py
Labels: improvement

#228 NXPY-214: Add a code coverage GitHub Action on PRs
  .github/workflows/unit_tests.yml
  CHANGELOG.rst
Labels: New feature

#229 NXPY-215: Add support for the JSON Web Token authentication
  CHANGELOG.rst
  examples/authentication.rst
  nuxeo/auth/__init__.py
  nuxeo/auth/jwt.py
  tests/test_auth.py
Labels: New feature

#230 NXPY-201: Implement support for OAuth2
  CHANGELOG.rst
  README.rst
  examples/authentication.rst
  nuxeo/auth/__init__.py
  nuxeo/auth/oauth2.py
  nuxeo/exceptions.py
  setup.cfg
  tests/test_auth.py
  tests/test_exception.py
  tox.ini
Labels: New feature

#231 NXPY-217: Restore Python 2.7 support
  .github/workflows/unit_tests.yml
  CHANGELOG.rst
  nuxeo/uploads.py
  tests/conftest.py
Labels: bug

#232 NXPY-201: Allow null endpoints
  examples/authentication.rst
  nuxeo/auth/oauth2.py
Labels: improvement

#233 NXPY-201: Allow more extensability of request_token()
  examples/authentication.rst
  nuxeo/auth/oauth2.py
  nuxeo/exceptions.py
  tests/test_exception.py
Labels: improvement

#234 NXPY-201: Move NuxeoClient._log_response() to utils.py::log_reponse()
  CHANGELOG.rst
  nuxeo/auth/oauth2.py
  nuxeo/client.py
  nuxeo/utils.py
  tests/test_log_response.py
Labels: improvement

#236 NXPY-216: Release 5.1.0
  CHANGELOG.rst
  nuxeo/__init__.py
  setup.cfg
Labels: release

#237 NXPY-216: Bump the version to 5.1.1
  CHANGELOG.rst
  nuxeo/__init__.py
  setup.cfg
Labels: release
